branchName: 'issue-${issue.number}-${issue.title[0,64],}'
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
