branchName: 'issue-${issue.number}-${issue.title[0,64],}'
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
branches:
  - label: hotfix
    name: main
    prefix: hotfix/
  - label: feature
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: build
    prefix: build/
  - label: refactor
    prefix: refactor/
  - label: test
    prefix: test/
  - label: docs
    prefix: docs/
  - label: release
    skipBranch: true
  - label: question
    skip: true
  - label: '*'
    prefix: issue/

